[ipynb taken from this video series](https://www.youtube.com/playlist?list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb)

In [1]:
import tensorflow as tf

In [2]:
print (tf.__version__)

2.13.0


## Initialization of Tensors

create a $1\times 1$ matrix in tf

In [5]:
x = tf.constant(4, shape = (1,1), dtype = tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


create a $2\times 3$ matrix

In [7]:
y = tf.constant([[1,2,3],[4,5,6]])
print(y)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


other initialization

In [8]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [9]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [10]:
x = tf.eye(3) # I for the identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


### Initialization of Distributions

In [11]:
x = tf.random.normal((3,3), mean = 0, stddev = 1)
print(x)

tf.Tensor(
[[-0.00414301  0.46212736  0.48329207]
 [ 0.90565526  0.01783551  0.59799355]
 [ 1.3582194   0.6547505   0.30153677]], shape=(3, 3), dtype=float32)


In [12]:
x = tf.random.uniform((1,3), minval = 0, maxval = 1)
print(x)

tf.Tensor([[0.3595947  0.9489039  0.38526046]], shape=(1, 3), dtype=float32)


In [13]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [16]:
x = tf.range(start = 1, limit = 10, delta = 2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [17]:
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


Data types in tf:
tf.float(16, 32, 64) \\
tf.int(8, 16, 32, 64) \\
tf.bool

## Mathematical Operations

In [19]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y) # equvalent: z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [21]:
z = tf.subtract(x, y) # or z = x - y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [22]:
z = tf.divide(x, y) # or z = x / y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [23]:
z = tf.multiply(x, y) # or z = x * y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [24]:
# dot product
z = tf.tensordot(x, y, axes = 1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [27]:
z = tf.reduce_sum(x*y, axis = 0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [28]:
z = x ** 5 # multiply each element by 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


### Matrix Multiplication

In [29]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[ 1.0917314   0.26641244 -0.4134475   0.74594605]
 [ 5.1019654  -0.06825334 -1.1253903   0.14236367]], shape=(2, 4), dtype=float32)


In [30]:
z = x @ y
print(z)

tf.Tensor(
[[ 1.0917314   0.26641244 -0.4134475   0.74594605]
 [ 5.1019654  -0.06825334 -1.1253903   0.14236367]], shape=(2, 4), dtype=float32)


## Indexing

In [34]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3]) # 1 inclusive and 3 exclusive, 0-based index
print(x[::2]) # print every 2 element
print(x[::-1]) # print in reverse order

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [35]:
# some more advanced indexing
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind) # extract elements at index 0 and index 3 of x

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [38]:
# in matrix
x = tf.constant([[1, 2],
                [3, 4],
                [5, 6]])
print(x[0,:]) # : means all
print(x[0:2,:]) # 0:2 means 0 inclusive and 2 exclusive, : means all

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Reshaping

In [39]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [41]:
# transpose
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
